### PR TITLE
Fix: Fix the breadcrumb

### LINKED ISSUE #407: Breadcrumbs links are not always correct
For example, in https://sonarwhal.com/docs/contributor-guide/getting-started/events/

if you click in "Documentation" it will actually take you to the "Contributor Guide":

image

### PR DESCRIPTION
**Pull request by qzhou1607**
## Pull request checklist

Make sure you:

- [ ] Signed the [Contributor License Agreement](https://cla.js.foundation/sonarwhal/sonarwhal)
- [ ] Followed the [commit message guidelines](https://sonarwhal.com/docs/contributor-guide/contributing/pull-requests/#commitmessages)

## Short description of the change(s)
Fix #407

### CODE REVIEW

File: src/sonarwhal-theme/helper/index.js [hunk 1]
```diff
@@ -242,6 +242,20 @@ module.exports = function () {
         getSortedToCTitles: (pages) => {
             return Object.keys(pages).sort();
         },
+        getTargetPagePath: (page, target) => {
+            const { category, permalink } = page;
```
Comment (molant) [inline src/sonarwhal-theme/helper/index.js]: Can you explain what is going on in here? It will be good to have some examples of inputs and outputs.

File: src/sonarwhal-theme/helper/index.js [hunk 2]
```diff
@@ -242,6 +242,20 @@ module.exports = function () {
...
+            const parts = permalink.split('/');
+            const targetPage = target === 'category' ? category : target;
+            let count = parts.length - parts.indexOf(targetPage) - 2;
+            let finalPath = '';
+
+            while (count) {
+                finalPath += '../';
+                count -= 1;
```
Comment (molant) [inline src/sonarwhal-theme/helper/index.js]: Let's do `count--;`

**Comment by molant** [comment]
@qzhou1607 you have a couple comments

**Comment by qzhou1607** [comment]
@molant Done.
